remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-algolia
  - toc